Hino.Salesforce.Admin/Controllers/EstablishmentController.cs
using System.Web.Mvc;

namespace Hino.Salesforce.Admin.Controllers
{
    //[RoutePrefix("establishment")]
    public class EstablishmentController : Controller
    {
        // GET: Establishment
        public ActionResult Index()
        {
            ViewBag.Message = "Estabelecimentos";
            return View();
        }

        // GET: Establishment Create
        public ActionResult Create()
        {
            ViewBag.Message = "Novo Estabelecimento";

            return View();
        }
        [HttpGet]
        public ActionResult Edit(long id, string pEstablishmentKey, string pKey)
        {
            ViewBag.Message = "Editar Estabelecimento";
            ViewBag.EstablishmentKey = pEstablishmentKey;
            ViewBag.UniqueKey = pKey;
            ViewBag.Id = id;

            return View();
        }
    }
}

Hino.Salesforce.Admin/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Hino.Salesforce.Admin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Devices()
        {
            ViewBag.Message = "Dispositivos";

            return View();
        }

        public ActionResult Establishment()
        {
            ViewBag.Message = "Estabelecimentos";

            return View();
        }
    }
}

Hino.Salesforce.Admin/Controllers/MordorController.cs
using System.Configuration;
using System.Web.Mvc;

namespace Hino.Salesforce.Admin.Controllers
{
    public class MordorController : Controller
    {
        // GET: Mordor
        public ActionResult Login()
        {
            ViewBag.HinoId = ConfigurationManager.AppSettings["Hino_Id"].ToString();
            return View();
        }

        // GET: Register
        public ActionResult Register()
        {
            return View();
        }
    }
}

Hino.Salesforce.Admin/Views/Establishment/Create.cshtml
@model Hino.Salesforce.Aplication.ViewModels.General.GEEstablishmentsCreateVM

@{
    ViewBag.Title = "Novo Estabelecimento";
}
<div class="row"
     ng-controller="EstablishmentController as EstablishmentCtrl">
    <h2>Estabelecimentos</h2>

    <form id="frmCreateEstablishment" 
          name="frmCreateEstablishment"
          ng-submit="EstablishmentCtrl.saveEstablishment()" novalidate>
        <div class="form-horizontal">
            <h4>Novo Estabelecimento</h4>
            <hr />
            <div class="form-group">
                <label class="control-label col-md-2" for="RazaoSocial">Raz&#227;o social *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="RazaoSocial"
                           name="RazaoSocial"
                           type="text"
                           ng-model="EstablishmentCtrl.establishment.RazaoSocial"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.RazaoSocial.$invalid && !frmCreateEstablishment.RazaoSocial.$pristine">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault, "Razão social")
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.RazaoSocial.MessageServer">
                        {{frmCreateEstablishment.RazaoSocial.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="NomeFantasia">Nome fantasia *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="NomeFantasia"
                           name="NomeFantasia"
                           type="text"
                           ng-model="EstablishmentCtrl.establishment.NomeFantasia"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.NomeFantasia.$invalid && !frmCreateEstablishment.NomeFantasia.$pristine">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault, "Nome fantasia")
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.NomeFantasia.MessageServer">
                        {{frmCreateEstablishment.NomeFantasia.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="Email">E-mail *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="Email"
                           name="Email"
                           type="email"
                           ng-model="EstablishmentCtrl.establishment.Email"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Email.$invalid && !frmCreateEstablishment.Email.$pristine &&
                          frmCreateEstablishment.Email.$error.required">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault, "E-mail")
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Email.$invalid && !frmCreateEstablishment.Email.$pristine &&
                          frmCreateEstablishment.Email.$error.email">
                        @Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.InvalidEmail
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Email.MessageServer">
                        {{frmCreateEstablishment.Email.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="Phone">Telefone *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="Phone"
                           name="Phone"
                           type="tel"
                           ng-minlength="14"
                           ng-maxlength="15"
                           minlength="14"
                           maxlength="15"
                           onkeydown="javascript:hinoApp.InputMask.fMasc(this, hinoApp.InputMask.mTel);"
                           ng-model="EstablishmentCtrl.establishment.Phone"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Phone.$invalid &&
                          !frmCreateEstablishment.Phone.$pristine&&
                          frmCreateEstablishment.Phone.$error.required">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault, "Telefone")
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Phone.$invalid &&
                          !frmCreateEstablishment.Phone.$pristine&&
                          frmCreateEstablishment.Phone.$error.minlength">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.PhoneInvalid, "Telefone")
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Phone.MessageServer">
                        {{frmCreateEstablishment.Phone.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="CNPJCPF">CNPJ *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="CNPJCPF"
                           name="CNPJCPF"
                           type="text"
                           ng-minlength="19"
                           ng-maxlength="19"
                           minlength="19"
                           maxlength="19"
                           onkeydown="javascript:hinoApp.InputMask.fMasc(this, hinoApp.InputMask.mCNPJ);"
                           ng-model="EstablishmentCtrl.establishment.CNPJCPF"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.CNPJCPF.$invalid && !frmCreateEstablishment.CNPJCPF.$pristine &&
                          frmCreateEstablishment.CNPJCPF.$error.required">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault, "CNPJ")
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.CNPJCPF.$invalid && !frmCreateEstablishment.CNPJCPF.$pristine &&
                          frmCreateEstablishment.CNPJCPF.$error.minlength">
                        @Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.InvalidCNPJ
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.CNPJCPF.MessageServer">
                        {{frmCreateEstablishment.CNPJCPF.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="Devices">N&#176; Dispositivos *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="Devices"
                           name="Devices"
                           type="number"
                           ng-model="EstablishmentCtrl.establishment.Devices"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Devices.$invalid && !frmCreateEstablishment.Devices.$pristine">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault, "N° Dispositivos")
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.Devices.MessageServer">
                        {{frmCreateEstablishment.Devices.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="PIS">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.PIS *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="PIS"
                           name="PIS"
                           type="number"
                           ng-model="EstablishmentCtrl.establishment.PIS"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.PIS.$invalid && !frmCreateEstablishment.PIS.$pristine">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault,
                                Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.PIS)
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.PIS.MessageServer">
                        {{frmCreateEstablishment.PIS.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" for="COFINS">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.COFINS *</label>
                <div class="col-md-10">
                    <input class="form-control text-box single-line"
                           id="COFINS"
                           name="COFINS"
                           type="number"
                           ng-model="EstablishmentCtrl.establishment.COFINS"
                           required />
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.COFINS.$invalid && !frmCreateEstablishment.COFINS.$pristine">
                        @string.Format(Hino.Salesforce.Infra.Cross.Resources.ValidationMessagesResource.RequiredDefault,
                                Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.COFINS)
                    </span>
                    <span class="field-validation-valid text-danger"
                          ng-show="frmCreateEstablishment.COFINS.MessageServer">
                        {{frmCreateEstablishment.COFINS.MessageServer}}
                    </span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <ul>
                        <li ng-repeat="err in EstablishmentCtrl.listErrors">
                            <span class="field-validation-valid text-danger">
                                {{ err.Messages[0] }}
                            </span>
                        </li>
                    </ul>

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                </div>
            </div>
        </div>
</form>


    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>
 </div>

Hino.Salesforce.Admin/Views/Establishment/Index.cshtml
@{
    ViewBag.Title = "Estabelecimentos";
}
<div class="row"
     ng-controller="EstablishmentController as EstablishmentCtrl"
     ng-init="EstablishmentCtrl.initList()">
    <h2>Establecimentos</h2>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.ActionLink("Novo", "Create", "Establishment", new { @class= "btn btn-default" })
                    </th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.RazaoSocial</th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.NomeFantasia</th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.CNPJCPF</th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.Email</th>
                </tr>
                <tr>
                    <th>&nbsp;</th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.Phone</th>
                    <th>@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.Devices</th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.Created</th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.Modified</th>
                    <th colspan="2">@Hino.Salesforce.Infra.Cross.Resources.FieldsNameResource.IsActive</th>

                </tr>
            </thead>
            <tbody>
                <tr class="row-table" ng-repeat-start="estab in EstablishmentCtrl.listEstablishments">
                    <td class="col-table">
                        <a class="btn btn-default" ng-href="/Establishment/Edit/{{ estab.Id }}/?pEstablishmentKey={{estab.EstablishmentKey}}&pKey={{ estab.UniqueKey }}&pId={{ estab.Id }}">Editar</a>
                    </td>
                    <td class="col-table" colspan="2">{{estab.RazaoSocial}}</td>
                    <td class="col-table" colspan="2">{{estab.NomeFantasia}}</td>
                    <td class="col-table" colspan="2">{{estab.CNPJCPF}}</td>
                    <td class="col-table" colspan="2">{{estab.Email}}</td>
                </tr>
                <tr ng-repeat-end>
                    <td class="col-table">
                        <button class="btn btn-danger" 
                                type="button"
                                ng-click="EstablishmentCtrl.deleteEstablishment(estab.EstablishmentKey, estab.UniqueKey, estab.Id)"
                                >Excluir</button>
                    </td>
                    <td class="col-table" colspan="2">{{estab.Phone}}</td>
                    <td class="col-table">{{estab.Devices}}</td>
                    <td class="col-table" colspan="2">{{estab.Created|date:"dd/MM/yyyy HH:mm"}}</td>
                    <td class="col-table" colspan="2">{{estab.Modified|date:"dd/MM/yyyy HH:mm"}}</td>
                    <td class="col-table" colspan="2">
                        <input id="ckeIsActive{{estab.Id}}" name="ckeIsActive{{estab.Id}}"
                               type="checkbox"
                               disabled="disabled"
                               ng-model="estab.IsActive"
                               value="{{estab.IsActive}}" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

Hino.Salesforce.Admin/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Hino.Salesforce.Admin/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hino.Salesforce.Admin/Views/Home/Devices.cshtml
@{
    ViewBag.Title = "Devices";
}

<h2>Devices</h2>

Hino.Salesforce.Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Hino Salesforce</h1>
    <p class="lead">Controle de empresas do aplicativo de vendas</p>
</div>

<!--<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>-->

Hino.Salesforce.Admin/Views/Mordor/Login.cshtml
@using Hino.Salesforce.Aplication.ViewModels.Auth
@model LoginVM
@{
    ViewBag.Title = "Login";
}


<div class="row"
     ng-controller="LoginController as LoginCtrl"
     ng-init="LoginCtrl.init()">
    <div class="col-md-offset-3 col-md-6 ">
        <h2>Login</h2>
        <section id="loginForm">
            <form class="form-horizontal" method="post" role="form">
                <h4>Informe seus dados para realizar o login</h4>
                <hr />
                @Html.Hidden("HinoId", (string)ViewBag.HinoId)
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        <input class="form-control" id="Email" name="Email" type="text" ng-model="LoginCtrl.user.user_email" />
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        <input class="form-control" id="Password" name="Password" type="password" ng-model="LoginCtrl.user.pass" />
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        <input type="submit" value="Entrar"
                               ng-click="LoginCtrl.btnAuthenticate()" 
                               class="btn btn-primary" />
                    </div>
                    <!--<div class="col-md-4">
                        Html.ActionLink("Primeiro acesso", "Register", new { }, new { class = "btn btn-default", role = "button" })
                    </div>-->
                </div>
                <!--<p>
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Esqueci minha senha", "ForgotPassword")
                    </div>                
                </p>-->
            </form>
        </section>
    </div>
</div>

Hino.Salesforce.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head lang="pt-br">
    <base href="/">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hino</title>
    <meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1"> <!-- media="(device-height: 568px)">-->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body ng-app="hinoApp"
      ng-controller="MainController as MainCtrl"
      ng-init="MainCtrl.init()">

    <div id="Modal" class="modal check-element animate-show-hide"
         ng-show="MainCtrl.showLoad || MainCtrl.showModal">
        <div class="lds-facebook" ng-show="MainCtrl.showLoad">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hino", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li ng-show="MainCtrl.isAuthenticated()">@Html.ActionLink("Estabelecimentos", "Index", "Establishment")</li>
                    <li ng-show="MainCtrl.isAuthenticated()" ><a style="cursor:pointer" ng-click="MainCtrl.LogOut()">Sair</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hino - Salesforce</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angular-touch")
    @Scripts.Render("~/bundles/angular-sanitize")
    @Scripts.Render("~/bundles/angular-route")
    @Scripts.Render("~/bundles/angular-resource")
    @Scripts.Render("~/bundles/angular-ext")
    @Scripts.Render("~/bundles/angular-messages")
    @Scripts.Render("~/bundles/angular-format")
    @Scripts.Render("~/bundles/angular-loader")
    @Scripts.Render("~/bundles/angular-cookies")
    @Scripts.Render("~/bundles/angular-aria")
    @Scripts.Render("~/bundles/angular-animate")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
</body>
</html>